language: rust
email:
  recipients:
    - trishume@gmail.com
  on_success: change # default: change
  on_failure: change # default: always
rust:
  - nightly
  - stable
script:
  - cargo build
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]
    then
      p=$(cd ./target/debug/build/onig_sys-*/out/lib/ && pwd)
      echo "adding $p to linker path"
      export LD_LIBRARY_PATH="${p}:${LD_LIBRARY_PATH}"
    fi
  - cargo test
  - make assets
  - rm -Rf examples
  - cargo doc
  # default features are required for examples to build - so remove them from sight.
  # Doc-tests may also use default features
  - rm -Rf examples && cargo test --lib --no-default-features
after_success: curl https://raw.githubusercontent.com/trishume/syntect/master/scripts/travis-doc-upload.sh | sh
