language: rust
email:
  recipients:
    - trishume@gmail.com
  on_success: change # default: change
  on_failure: change # default: always
rust:
  - nightly
  - stable
script:
  - cargo build
  - cargo doc
  - cargo test
after_success: curl https://raw.githubusercontent.com/trishume/syntect/master/scripts/travis-doc-upload.sh | sh
